const workoutPlan = [
  { id:'seg', day:1, name:'Peito superior + ombros + tríceps', short:'Peito + ombro', exercises:[
    ['supino-inclinado','Supino inclinado','Smith + banco a ~30°',4,8,10,90,'🏋️'],
    ['desenvolvimento','Desenvolvimento sentado','Halteres + banco',3,8,12,90,'⬆️'],
    ['elevacao-lateral','Elevação lateral unilateral','Polia baixa / crossover',4,12,15,60,'🪽'],
    ['crucifixo-baixo-alto','Crucifixo baixo → alto','Crossover',3,12,15,60,'✖️'],
    ['triceps-pushdown','Tríceps pushdown','Polia alta + barra/corda',3,10,15,60,'💪'],
    ['triceps-overhead','Tríceps acima da cabeça','Polia alta + corda',2,12,15,60,'🔝'] ]},
  { id:'ter', day:2, name:'Pernas completas', short:'Pernas', exercises:[
    ['leg-press','Leg press 45°','Leg press 45°',4,8,12,90,'🦵'],
    ['agachamento-smith','Agachamento','Smith',3,8,12,90,'🏋️'],
    ['extensora','Cadeira extensora','Máquina extensora',3,10,15,60,'🦵'],
    ['flexora','Flexora sentada','Máquina flexora',3,10,15,60,'🦿'],
    ['abdutora','Abdutora','Máquina adutora/abdutora',3,15,20,60,'↔️'],
    ['panturrilha','Panturrilha no leg press','Leg press',3,12,20,60,'🦶'] ]},
  { id:'qua', day:3, name:'Costas + bíceps + abdômen', short:'Costas + bíceps', exercises:[
    ['puxada-aberta','Puxada alta aberta','Máquina de puxada',4,8,12,90,'🔻'],
    ['remada-baixa','Remada baixa','Polia baixa / crossover',4,8,12,90,'🚣'],
    ['pullover','Pullover braços estendidos','Polia alta',3,10,15,60,'⬇️'],
    ['crucifixo-inverso','Crucifixo inverso','Duas polias do crossover',3,12,15,60,'🪽'],
    ['rosca-polia','Rosca bíceps','Polia baixa',3,10,15,60,'💪'],
    ['rosca-martelo','Rosca martelo','Halteres',2,10,12,60,'🔨'],
    ['crunch','Crunch ajoelhado','Polia alta + corda',3,10,15,60,'◼️'] ]},
  { id:'qui', day:4, name:'Peito + ombro estético + braços', short:'Peito + braços', exercises:[
    ['supino-reto','Supino reto','Smith + banco reto',3,8,12,90,'🏋️'],
    ['crucifixo-reto','Crucifixo na linha do peito','Crossover',3,10,15,60,'✖️'],
    ['elevacao-lateral-2','Elevação lateral','Polia',4,12,15,60,'🪽'],
    ['face-pull','Face pull','Polia alta + corda',3,12,15,60,'🎯'],
    ['triceps-overhead-2','Tríceps acima da cabeça','Polia + corda',3,10,15,60,'🔝'],
    ['rosca-unilateral','Rosca bíceps unilateral','Polia baixa',2,10,15,60,'💪'] ]},
  { id:'sex', day:5, name:'Posterior + costas + ombros + abdômen', short:'Posterior + costas', exercises:[
    ['rdl','Stiff / RDL','Smith',3,8,12,90,'↘️'],
    ['flexora-2','Flexora','Máquina flexora',3,10,15,60,'🦿'],
    ['leg-press-alto','Leg press — pés mais altos','Leg press 45°',3,10,12,90,'🦵'],
    ['puxada-neutra','Puxada neutra / fechada','Máquina de puxada',3,10,12,90,'🔻'],
    ['elevacao-lateral-3','Elevação lateral','Polia',3,12,15,60,'🪽'],
    ['abdutora-2','Abdutora','Máquina adutora/abdutora',2,15,20,60,'↔️'],
    ['crunch-2','Crunch na polia','Polia alta',3,10,15,60,'◼️'] ]}
].map(w=>({...w, exercises:w.exercises.map(e=>({id:e[0],name:e[1],equipment:e[2],sets:e[3],min:e[4],max:e[5],rest:e[6],icon:e[7]}))}));

const K={sessions:'v60_sessions', body:'v60_body', settings:'v60_settings', draft:'v60_draft'};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const load=(k,def)=>{try{return JSON.parse(localStorage.getItem(k))??def}catch{return def}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const state={page:'home', activeSession:null, restTimer:null, restRemaining:0, installPrompt:null};
const settings=()=>load(K.settings,{restSound:true,defaultRest:60});
const sessions=()=>load(K.sessions,[]); const body=()=>load(K.body,[]);

function fmtDate(d){return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(d)}
function fmtFull(d){return new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long'}).format(d)}
function todayWorkout(){const day=new Date().getDay();return workoutPlan.find(w=>w.day===day)||workoutPlan[0]}
function getLastSession(workoutId){return sessions().filter(s=>s.workoutId===workoutId&&s.finishedAt).sort((a,b)=>b.startedAt-a.startedAt)[0]}
function lastExercisePerf(exId){const ss=sessions().filter(s=>s.finishedAt).sort((a,b)=>b.startedAt-a.startedAt);for(const s of ss){const ex=s.exercises.find(e=>e.id===exId);if(ex)return ex}return null}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function nav(){return `<nav class="bottom-nav">${[['home','⌂','Hoje'],['workouts','▦','Treinos'],['progress','↗','Progresso'],['body','◉','Corpo'],['settings','⚙','Config']].map(([p,i,l])=>`<button class="nav-btn ${state.page===p?'active':''}" data-nav="${p}"><span class="ico">${i}</span><span>${l}</span></button>`).join('')}</nav>`}
function shell(content){$('#app').innerHTML=`<main class="app-shell"><header class="topbar"><div class="brand"><div class="brand-mark">V</div><div><h1>V60</h1><p>shape V · 5x por semana</p></div></div><span class="pill">${fmtDate(new Date())}</span></header>${content}${state.page!=='session'?nav():''}</main>`;bindCommon()}
function bindCommon(){$$('[data-nav]').forEach(b=>b.onclick=()=>{state.page=b.dataset.nav;render()});}

function renderHome(){const w=todayWorkout();const ss=sessions();const weekStart=new Date();const diff=(weekStart.getDay()+6)%7;weekStart.setDate(weekStart.getDate()-diff);weekStart.setHours(0,0,0,0);const weekSessions=ss.filter(s=>s.finishedAt&&s.startedAt>=weekStart.getTime());const totalMin=Math.round(weekSessions.reduce((a,s)=>a+(s.duration||0),0)/60);const sets=weekSessions.reduce((a,s)=>a+s.exercises.reduce((x,e)=>x+e.sets.filter(z=>z.done).length,0),0);const streak=calcStreak(ss);const last=getLastSession(w.id);
 shell(`<section class="hero"><div class="eyebrow">treino de hoje</div><h2>${w.name}</h2><p>${w.exercises.length} exercícios · foco estético · ${last?'último treino '+fmtDate(new Date(last.startedAt)):'primeira sessão registrada'}</p><div class="hero-actions"><button class="btn btn-primary" id="startToday">Começar treino</button><button class="btn btn-secondary" id="viewToday">Ver exercícios</button></div></section>
 <section class="section"><div class="section-head"><div><h3>Esta semana</h3><p>consistência antes de perfeição</p></div></div><div class="week-row">${workoutPlan.map(x=>{const done=weekSessions.some(s=>s.workoutId===x.id);return `<div class="day-dot ${done?'done':''} ${x.id===w.id?'today':''}">${x.id.toUpperCase()}<br>${done?'✓':'·'}</div>`}).join('')}</div></section>
 <section class="section"><div class="grid stats"><div class="card"><div class="stat-value">${weekSessions.length}</div><div class="stat-label">treinos na semana</div></div><div class="card"><div class="stat-value">${sets}</div><div class="stat-label">séries concluídas</div></div><div class="card"><div class="stat-value">${totalMin}</div><div class="stat-label">minutos treinados</div></div><div class="card"><div class="stat-value">${streak}</div><div class="stat-label">dias de sequência</div></div></div></section>
 <section class="section"><div class="section-head"><div><h3>Prioridade do shape</h3><p>o que mais muda sua silhueta</p></div></div><div class="grid"><div class="card"><div class="stat-value">01</div><b>Ombro lateral</b><p class="muted small">Mais largura e contraste com a cintura.</p></div><div class="card"><div class="stat-value">02</div><b>Dorsal + peito superior</b><p class="muted small">Formato em V e tronco mais preenchido.</p></div></div></section>`);
 $('#startToday').onclick=()=>startSession(w.id);$('#viewToday').onclick=()=>{state.page='workouts';state.selectedWorkout=w.id;render()};
}

function renderWorkouts(){const selected=workoutPlan.find(w=>w.id===(state.selectedWorkout||todayWorkout().id));shell(`<div class="page-title"><div><h2>Treinos</h2><p>5 dias · aproximadamente 60 minutos</p></div></div><div class="grid">${workoutPlan.map((w,i)=>`<div class="card workout-card ${w.id===selected.id?'active':''}" data-workout="${w.id}"><div class="num">${i+1}</div><h4>${w.name}</h4><p>${w.exercises.length} exercícios</p></div>`).join('')}</div><section class="section"><div class="section-head"><div><h3>${selected.name}</h3><p>${selected.exercises.length} exercícios</p></div><button class="btn btn-primary" id="startSelected">Iniciar</button></div><div class="exercise-list">${selected.exercises.map(ex=>`<div class="exercise"><div class="ex-icon">${ex.icon}</div><div><h4>${ex.name}</h4><p>${ex.equipment}</p><span class="tag">${ex.sets} × ${ex.min}-${ex.max}</span></div><div class="meta">${ex.rest}s<br><span class="muted">descanso</span></div></div>`).join('')}</div></section>`);$$('[data-workout]').forEach(el=>el.onclick=()=>{state.selectedWorkout=el.dataset.workout;renderWorkouts()});$('#startSelected').onclick=()=>startSession(selected.id)}

function calcStreak(ss){const days=[...new Set(ss.filter(s=>s.finishedAt).map(s=>new Date(s.startedAt).toISOString().slice(0,10)))].sort().reverse();if(!days.length)return 0;let streak=1;let prev=new Date(days[0]);for(let i=1;i<days.length;i++){const d=new Date(days[i]);const delta=Math.round((prev-d)/86400000);if(delta===1){streak++;prev=d}else if(delta>1)break}return streak}

function startSession(workoutId){const w=workoutPlan.find(x=>x.id===workoutId);const draft=load(K.draft,null);if(draft&&draft.workoutId===workoutId&&!draft.finishedAt&&confirm('Existe um treino em andamento. Continuar de onde parou?')){state.activeSession=draft}else{state.activeSession={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),workoutId,wName:w.name,startedAt:Date.now(),exercises:w.exercises.map(ex=>({...ex,sets:Array.from({length:ex.sets},(_,i)=>({n:i+1,weight:'',reps:'',done:false}))}))};save(K.draft,state.activeSession)}state.page='session';renderSession()}
function sessionElapsed(){return state.activeSession?Math.floor((Date.now()-state.activeSession.startedAt)/1000):0}
function fmtClock(sec){const m=Math.floor(sec/60),s=sec%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function sessionProgress(){const all=state.activeSession.exercises.flatMap(e=>e.sets);return all.length?Math.round(all.filter(s=>s.done).length/all.length*100):0}
function suggestion(ex){const last=lastExercisePerf(ex.id);if(!last)return 'Primeira referência deste exercício.';const valid=last.sets.filter(s=>s.done);if(valid.length&&valid.every(s=>Number(s.reps)>=ex.max))return 'Última sessão bateu o topo da faixa. Considere subir um pouco a carga.';return 'Tente manter a carga e ganhar repetições com boa técnica.'}
function renderSession(){const s=state.activeSession;if(!s){state.page='home';render();return}const pct=sessionProgress();$('#app').innerHTML=`<main class="app-shell"><div class="session-header"><div class="session-top"><div><div class="eyebrow">modo academia</div><b>${s.wName}</b></div><div class="timer-chip" id="sessionTime">${fmtClock(sessionElapsed())}</div></div><div class="session-progress"><div style="width:${pct}%"></div></div></div>${s.exercises.map((ex,ei)=>{const last=lastExercisePerf(ex.id);const lastText=last?last.sets.filter(x=>x.done).map(x=>`${x.weight||'—'}kg × ${x.reps||'—'}`).join(' · '):'sem histórico';return `<article class="session-ex"><div class="session-ex-head"><div class="ex-icon">${ex.icon}</div><div><h3>${ei+1}. ${ex.name}</h3><div class="sub">${ex.equipment} · alvo ${ex.sets} × ${ex.min}-${ex.max}</div></div></div><div class="last-note"><b>Último:</b> ${lastText}<br><span class="suggestion">${suggestion(ex)}</span></div><div class="set-grid header"><div>#</div><div>Carga kg</div><div>Reps</div><div>OK</div></div>${ex.sets.map((set,si)=>`<div class="set-grid"><div class="set-num">${si+1}</div><input class="field" type="number" inputmode="decimal" step="0.5" data-weight="${ei}-${si}" value="${set.weight}" placeholder="kg"><input class="field" type="number" inputmode="numeric" data-reps="${ei}-${si}" value="${set.reps}" placeholder="reps"><button class="set-check ${set.done?'done':''}" data-check="${ei}-${si}">${set.done?'✓':'○'}</button></div>`).join('')}</article>`}).join('')}<div style="display:flex;gap:10px;margin:18px 0 4px"><button class="btn btn-primary" style="flex:1" id="finishSession">Finalizar treino</button><button class="btn btn-danger" id="cancelSession">Cancelar</button></div></main><div class="rest-bar ${state.restRemaining>0?'show':''}" id="restBar"><div><div class="small muted">descanso</div><div class="rest-time" id="restTime">${fmtClock(state.restRemaining)}</div></div><button class="btn btn-secondary" id="skipRest">Pular</button></div>`;
 $$('[data-weight]').forEach(i=>i.oninput=()=>updateSetField(i.dataset.weight,'weight',i.value));$$('[data-reps]').forEach(i=>i.oninput=()=>updateSetField(i.dataset.reps,'reps',i.value));$$('[data-check]').forEach(b=>b.onclick=()=>toggleSet(b.dataset.check));$('#finishSession').onclick=finishSession;$('#cancelSession').onclick=cancelSession;$('#skipRest')?.addEventListener('click',stopRest);clearInterval(state.sessionClock);state.sessionClock=setInterval(()=>{const el=$('#sessionTime');if(el)el.textContent=fmtClock(sessionElapsed())},1000);if(state.restRemaining>0)beginRestTicker();}
function updateSetField(key,field,value){const [ei,si]=key.split('-').map(Number);state.activeSession.exercises[ei].sets[si][field]=value;save(K.draft,state.activeSession)}
function toggleSet(key){const [ei,si]=key.split('-').map(Number);const set=state.activeSession.exercises[ei].sets[si];set.done=!set.done;save(K.draft,state.activeSession);if(set.done){const ex=state.activeSession.exercises[ei];startRest(ex.rest)}renderSession()}
function startRest(seconds){state.restRemaining=seconds;beginRestTicker()}
function beginRestTicker(){clearInterval(state.restTimer);state.restTimer=setInterval(()=>{state.restRemaining--;const el=$('#restTime');if(el)el.textContent=fmtClock(Math.max(0,state.restRemaining));if(state.restRemaining<=0){stopRest();toast('Descanso concluído')}} ,1000)}
function stopRest(){clearInterval(state.restTimer);state.restRemaining=0;$('#restBar')?.classList.remove('show')}
function finishSession(){const s=state.activeSession;const total=s.exercises.flatMap(e=>e.sets).length;const done=s.exercises.flatMap(e=>e.sets).filter(x=>x.done).length;if(done===0&&!confirm('Nenhuma série foi marcada. Finalizar mesmo assim?'))return;s.finishedAt=Date.now();s.duration=Math.floor((s.finishedAt-s.startedAt)/1000);const all=sessions();all.push(s);save(K.sessions,all);localStorage.removeItem(K.draft);state.activeSession=null;stopRest();clearInterval(state.sessionClock);state.page='progress';toast('Treino salvo ✓');render()}
function cancelSession(){if(!confirm('Cancelar este treino? O rascunho será apagado.'))return;localStorage.removeItem(K.draft);state.activeSession=null;stopRest();clearInterval(state.sessionClock);state.page='home';render()}

function renderProgress(){const ss=sessions().filter(s=>s.finishedAt).sort((a,b)=>b.startedAt-a.startedAt);const exOptions=[...new Map(workoutPlan.flatMap(w=>w.exercises).map(e=>[e.id,e])).values()];const selected=state.progressEx||exOptions[0].id;const points=[];ss.slice().reverse().forEach(s=>{const ex=s.exercises.find(e=>e.id===selected);if(ex){const weights=ex.sets.filter(z=>z.done&&Number(z.weight)>0).map(z=>Number(z.weight));if(weights.length)points.push({date:new Date(s.startedAt),value:Math.max(...weights)})}});const max=Math.max(1,...points.map(p=>p.value));shell(`<div class="page-title"><div><h2>Progresso</h2><p>carga, frequência e histórico</p></div></div><div class="form-card"><label>Exercício</label><select id="progressEx">${exOptions.map(e=>`<option value="${e.id}" ${e.id===selected?'selected':''}>${e.name}</option>`).join('')}</select></div><div class="chart">${points.length?points.slice(-10).map(p=>`<div class="bar" style="height:${Math.max(10,p.value/max*100)}%"><span>${p.value}kg</span></div>`).join(''):'<div class="empty" style="width:100%;align-self:stretch;display:grid;place-items:center">Registre carga e conclua séries para ver o gráfico.</div>'}</div><section class="section"><div class="section-head"><div><h3>Histórico</h3><p>${ss.length} sessões concluídas</p></div></div>${ss.length?ss.slice(0,20).map(s=>`<div class="history-item"><div><h4>${s.wName}</h4><p>${fmtFull(new Date(s.startedAt))}</p></div><strong>${Math.round((s.duration||0)/60)} min</strong></div>`).join(''):'<div class="empty">Seu histórico vai aparecer aqui depois do primeiro treino.</div>'}</section>`);$('#progressEx').onchange=e=>{state.progressEx=e.target.value;renderProgress()}}

function renderBody(){const entries=body().sort((a,b)=>b.date.localeCompare(a.date));const latest=entries[0];shell(`<div class="page-title"><div><h2>Corpo</h2><p>acompanhe medidas sem obsessão diária</p></div></div><div class="grid stats"><div class="card"><div class="stat-value">${latest?.weight||'—'}</div><div class="stat-label">peso kg</div></div><div class="card"><div class="stat-value">${latest?.waist||'—'}</div><div class="stat-label">cintura cm</div></div><div class="card"><div class="stat-value">${latest?.chest||'—'}</div><div class="stat-label">peito cm</div></div><div class="card"><div class="stat-value">${latest?.arm||'—'}</div><div class="stat-label">braço cm</div></div></div><section class="section"><div class="form-card"><h3 style="margin-top:0">Nova medição</h3><div class="form-row"><div><label>Data</label><input id="bodyDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div><label>Peso (kg)</label><input id="bodyWeight" type="number" step="0.1" inputmode="decimal"></div><div><label>Cintura (cm)</label><input id="bodyWaist" type="number" step="0.1" inputmode="decimal"></div><div><label>Peito (cm)</label><input id="bodyChest" type="number" step="0.1" inputmode="decimal"></div><div><label>Braço (cm)</label><input id="bodyArm" type="number" step="0.1" inputmode="decimal"></div></div><button class="btn btn-primary" id="saveBody" style="margin-top:12px">Salvar medição</button></div></section><section class="section"><h3>Histórico de medidas</h3>${entries.length?entries.slice(0,15).map(e=>`<div class="history-item"><div><h4>${new Intl.DateTimeFormat('pt-BR').format(new Date(e.date+'T12:00:00'))}</h4><p>${[e.weight&&e.weight+' kg',e.waist&&'cintura '+e.waist,e.chest&&'peito '+e.chest,e.arm&&'braço '+e.arm].filter(Boolean).join(' · ')}</p></div></div>`).join(''):'<div class="empty" style="margin-top:12px">Nenhuma medição ainda.</div>'}</section>`);$('#saveBody').onclick=()=>{const entry={id:Date.now(),date:$('#bodyDate').value,weight:$('#bodyWeight').value,waist:$('#bodyWaist').value,chest:$('#bodyChest').value,arm:$('#bodyArm').value};if(!entry.date)return toast('Escolha uma data');const all=body();all.push(entry);save(K.body,all);toast('Medição salva');renderBody()}}

function renderSettings(){const st=settings();const draft=load(K.draft,null);shell(`<div class="page-title"><div><h2>Configurações</h2><p>ajustes do seu treino</p></div></div><div class="form-card"><h3 style="margin-top:0">Aplicativo</h3><label>Descanso padrão (segundos)</label><input id="restDefault" type="number" min="30" max="180" step="15" value="${st.defaultRest||60}"><div class="divider"></div><button class="btn btn-secondary" id="installBtn">Instalar no celular</button></div><div class="form-card"><h3 style="margin-top:0">Dados</h3><p class="muted small">Esta versão salva tudo neste navegador. Você pode exportar um backup em JSON.</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn btn-secondary" id="exportData">Exportar backup</button><label class="btn btn-ghost" style="cursor:pointer">Importar<input id="importData" type="file" accept="application/json" class="hidden"></label></div>${draft?'<div class="divider"></div><button class="btn btn-danger" id="clearDraft">Apagar treino em andamento</button>':''}</div><div class="form-card"><h3 style="margin-top:0">Próxima evolução</h3><p class="muted small">Login + Supabase, sincronização entre celular e PC, fotos de evolução e notificações podem entrar na próxima versão sem mudar a lógica do treino.</p></div>`);$('#restDefault').onchange=e=>save(K.settings,{...st,defaultRest:Number(e.target.value)});$('#installBtn').onclick=installApp;$('#exportData').onclick=exportData;$('#importData').onchange=importData;if($('#clearDraft'))$('#clearDraft').onclick=()=>{localStorage.removeItem(K.draft);toast('Rascunho apagado');renderSettings()}}
function installApp(){if(state.installPrompt){state.installPrompt.prompt();state.installPrompt.userChoice.finally(()=>state.installPrompt=null)}else{alert('No iPhone: Safari → Compartilhar → Adicionar à Tela de Início. No Android/Chrome: menu do navegador → Instalar app.') }}
function exportData(){const data={sessions:sessions(),body:body(),settings:settings(),exportedAt:new Date().toISOString()};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='v60-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(d.sessions)save(K.sessions,d.sessions);if(d.body)save(K.body,d.body);if(d.settings)save(K.settings,d.settings);toast('Backup importado');render()}catch{alert('Arquivo inválido')}};r.readAsText(f)}

function render(){switch(state.page){case'home':renderHome();break;case'workouts':renderWorkouts();break;case'progress':renderProgress();break;case'body':renderBody();break;case'settings':renderSettings();break;case'session':renderSession();break}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
